// solidstart/src/routes/discussions/[id].tsx
import {For, createMemo} from "solid-js";
import {RouteDataArgs, Title, useRouteData} from "solid-start";
import {createServerData$} from "solid-start/server";
import {AddReaction} from "~/components/AddReaction";
import {REACTION_EMOJI, getDiscussionComments, getDiscussionDetails} from "~/lib/github/discussions";

export function routeData({ params }: RouteDataArgs) {
  return createServerData$(id => {
    const discussionId = Number(id);
    return Promise.all([getDiscussionDetails(discussionId), getDiscussionComments(discussionId)]).then(data => {
      return {discussion: data[0], comments: data[1]};
    })
  }, {key: () => params.id});
}

export default function Discussions() {
  const discussionAndComments = useRouteData<typeof routeData>();
  const reactions = createMemo(() => discussionAndComments()?.discussion.reactionGroups.filter((group) => group.totalCount > 0));
  const discussion = () => discussionAndComments()?.discussion;
  const comments = () => discussionAndComments()?.comments;
  
  return (
    <main>
      <Title> - Discussions</Title>
      <section>
        <h1>{discussion()?.title}</h1>
        <p>by {discussion()?.author} on {discussion()?.createdAt}</p>
        <div innerHTML={discussion()?.bodyHTML} />
        <div class="reactions">
          <For each={reactions()}>
            {(group) => <button disabled>{REACTION_EMOJI[group.content]}{group.totalCount}</button>}
          </For>
          <AddReaction />
        </div>
        <div class="comments">
          <h2>Comments</h2>
          <ul>
            <For each={comments()}>
              {(comment) => <div innerHTML={comment.bodyHTML}></div>}
            </For>  
		      </ul>
        </div>
      </section>
    </main>
  );
}

// qwikcity/src/routes/discussions/[id]/index.tsx
import { component$ } from "@builder.io/qwik";
import { routeLoader$ } from "@builder.io/qwik-city";
import AddReaction from "~/components/discussions/AddReaction";
import {
  REACTION_EMOJI,
  getDiscussionComments,
  getDiscussionDetails,
} from "~/lib/github/discussions";

export const useDiscussion = routeLoader$(async (requestEvent) =>
  getDiscussionDetails(Number(requestEvent.params.id))
);
export const useComments = routeLoader$(async (requestEvent) =>
  getDiscussionComments(Number(requestEvent.params.id))
);

export default component$(() => {
  const discussion = useDiscussion();
  const comments = useComments();

  return (
    <>
      <section>
        <h1>{discussion.value.title}</h1>
        <p>
          by {discussion.value.author} on {discussion.value.createdAt}
        </p>
        <div dangerouslySetInnerHTML={discussion.value.bodyHTML} />
        <div class="reactions">
          {discussion.value.reactionGroups.map((group) => (
            <button disabled>
              {REACTION_EMOJI[group.content]}
              {group.totalCount}
            </button>
          ))}
          <AddReaction />
        </div>
        <div class="comments">
          <h2>Comments</h2>
          <ul>
            {comments.value.map((comment) => (
              <div dangerouslySetInnerHTML={comment.bodyHTML}></div>
            ))}
          </ul>
        </div>
      </section>
    </>
  );
});
